feat tests: use userver requirements
userver-framework/service_template pull request #61
Opened 2023-12-12 10:53 UTC by Anton3

Also, correct Makefile to support Ninja generator (avoid direct usage of low-level make).

2023-12-12 12:52 UTC, alexiprof requested changes

2023-12-12 12:52 UTC, alexiprof commented on Makefile
> +	@cmake -B build_debug $(CMAKE_DEBUG_FLAGS)
CMAKE_COMMON_FLAGS потерял

2023-12-12 13:00 UTC, Anton3 commented on Makefile
> +	@cmake -B build_debug $(CMAKE_DEBUG_FLAGS)
См. строки 12, 13

2023-12-13 09:20 UTC, apolukhin approved these changes

2023-12-13 16:50 UTC, alexiprof approved these changes

2023-12-13 16:51 UTC, merged